name: NovaCart CI

on:
  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:

jobs:
  build:

    name: Build, Test, Coverage & SonarQube

    runs-on: self-hosted

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\${{ env.USERNAME }}\.gradle\caches
            C:\Users\${{ env.USERNAME }}\.gradle\wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Execute Permission
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build, Test, Generate Coverage & Sonar Analysis
        shell: powershell
        run: |
          .\gradlew.bat clean build jacocoTestReport sonar

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco
          retention-days: 7